# Generated by Django 4.2 on 2023-05-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_customuser_courses_registered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
