# Generated by Django 4.2 on 2023-05-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codes', models.CharField(max_length=100)),
                ('codenumber', models.CharField(max_length=20)),
            ],
        ),
    ]
