# Generated by Django 4.2 on 2023-05-03 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendancenumber',
        ),
    ]
