# Generated by Django 4.2 on 2023-05-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_attendance_attendancenumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='Attendancemodel',
        ),
    ]
